### ISSUE TITLE
Anyway this could be turned into a native app?

### ISSUE THREAD

**Issue by driftywinds** [cioraneanu/firefly-pico#110]
Are there plans to make this a native app for Android?

**Comment by cioraneanu** [comment]
The app has PWA support and can already be installed on your home screen.
Having separate Kotlin, Swift and JS repositories (for all platforms) is a ton of work and I'm not seeing any great benefits 😇

**Comment by Gugi264** [comment]
I dont know anything about PWA's, but when I install pico as a PWA all it does is open my browser with the url of my instance.
Other PWA's dont open in my browser but in their own I guess? Anyhow they feel more like an native app because of that.

So any chance to change the PWA so it runs in its own fullscreen browser?

**Comment by cioraneanu** [comment]
I don't have an Android phone to test it, maybe someone else can help with that?

On iOS it works as expected. 
![pwa](https://github.com/user-attachments/assets/e6e49fa9-01d9-4619-a0b7-510043fba697)
