### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by Call-Me-G-Now** [cioraneanu/firefly-pico#24]
Would love a dark mode.

Any tips on where/how i can get started?

**Comment by cioraneanu** [comment]
Uuuuu you're really brave! 😃
My CSS was not told that this repo will be public and that people will want a dark theme :))

Basically we need to change all hard coded collors to CSS variables.  Most of the changes must be done to  `front/assets/style/theme.css` and there are some inline styles applied in Vue components directly. 

I've created a starting point for you here: [Commit 43f6948](https://github.com/cioraneanu/firefly-pico/tree/43f69483de04f4e9ee8a1b9ca87ac0ee80744ac0). It's on the branch that I'm currently playing with since I've made a new page` Settings -> UI Preferences` and the theme changing button would be a good fit there. I've written the theme switching logic so you can focus on the CSS part.

The CSS variables defined by the main Vant theme are [here](https://github.com/youzan/vant/blob/main/packages/vant/src/style/css-variables.less#L81)

If you need any more custom colors you can add them in `front/assets/style/variables.css` 

To run the project locally just:
```
cd front
npm i
npm start
```

Let me know if you need anything else 👍

**Comment by Call-Me-G-Now** [comment]
made some progress.

I'm stuck with trying to overwrite existing vars. For example, some muted texts. In the std dark theme they're a little too dark.
I tried adding `--van-text-color-3` to `variables.css` but that won't override it.
I think overwriting these is the best solution as otherwise all `--van-text-color-3` references need to changed to a new var.

Any pointers on how to override these existing vars?

**Comment by cioraneanu** [comment]
The `vant` UI library is loaded inside `nuxt.config.ts` via modules so its CSS get appended after the ones defined in the same file. 

One solution: Remove  `@/assets/styles/variables.css` from `nuxt.config.ts` and add `import '~/assets/styles/variables.css'` inside `app.vue`.

**Comment by Call-Me-G-Now** [comment]
ok that works :+1: 

Any chance you can share your dev setup? wanna test with transactions etc but just wanna link this against my existing ff3.

**Comment by cioraneanu** [comment]
Will have to write a Development readme section section soon. 🙈 

For your scenario since you don't make changes to the backend you can just start the frontend as described above. Go to `Settings -> App Config` set` Pico backend url` to your running Pico Docker Container.

**Comment by Call-Me-G-Now** [comment]
> Will have to write a Development readme section section soon. 🙈
> 

No worries, we're all just having fun.

> For your scenario since you don't make changes to the backend you can just start the frontend as described above. Go to `Settings -> App Config` set` Pico backend url` to your running Pico Docker Container.

ooh :man_facepalming: .... should've thought of that. my bad. Will try :+1:

**Comment by Call-Me-G-Now** [comment]
opened #57 for a part II of Dark mode fixes

**Comment by cioraneanu** [comment]
Implement in 13c159a1151abdc93cf56d0f57914efc65b340c3

**Comment by Call-Me-G-Now** [comment]
looking good :+1:
