### ISSUE TITLE
[Suggestion] Make Pico a PWA

### ISSUE THREAD

**Issue by avee87** [cioraneanu/firefly-pico#25]
Progressive Web Apps have special treatment on iOS at least and it would be great to have it.

**Comment by cioraneanu** [comment]
I want this as well but I'm waiting for the official Nuxt3 PWA module to be ready.
[Nuxt Roadmap](https://nuxt.com/docs/community/roadmap#roadmap)

**Comment by avee87** [comment]
What's wrong with using existing solutions for that? Looks like you even have some commented-out PWA setup here: https://github.com/cioraneanu/firefly-pico/blob/main/front/nuxt.config.ts#L75-L143

**Comment by cioraneanu** [comment]
Because I've played around in the past with 2 such modules in the attempt to make the app work offline + installable on mobile and I didn't have much success with it. There was also a huge list of ideas that would make the app better so this one got delayed.

If you want to give it a go you're welcome to do so.

**Comment by cioraneanu** [comment]
Added  in #26. 

Note: 
- Will still need to test if service worker cache behaves correctly when releasing a new version
- Will need to find a way to set `theme_color` and `background_color` at runtime based on active theme.
