### ISSUE TITLE
[Suggestion] Budgets

### ISSUE THREAD

**Issue by markymark501998** [cioraneanu/firefly-pico#72]
What's the general consensus around adding support for just budgets? I see #13 is closed, but figured I'd start a new item focused solely on this topic.

**Comment by cioraneanu** [comment]
Thanks for creating a separate issue for this 😃  
Budget management will be added in the future but since I'm not using them, other features will have priority.  😇 

My first thought about implementing this:
- add 2 new pages in "extras": one to list budgets, one to create/edit a budget
- create a budgets card on the dashboard. Show it if only a user has some budgets defined.
- In the transaction adding form show the new budget selector only if a user has budgets defined

Any other ideas on what to change to make this easier / better?

**Comment by markymark501998** [comment]
Understandable. I am thinking of cracking open the code and trying to implement this myself because I love this interface, but use budgets quite a bit for tracking.

Only tweak I would say is maybe unify the two "extras" pages? The one list page would act as a CRUD controller.

**Comment by cioraneanu** [comment]
Having a scrollable list of editable forms would go against the current UX pattern so I'm not a fan of that.

**Comment by markymark501998** [comment]
Couldn't agree more - what about a scrollable list of the budget names (+ maybe $ total / other summary-type information). Similar to extras/categories and extras/tags, the form doesn't pop up until clicked and it doesn't introduce a new UX pattern.

Thoughts?

**Comment by cioraneanu** [comment]
Perfect 😇

**Comment by cioraneanu** [comment]
Impplemented in 1.4.0

**Comment by markymark501998** [comment]
Already pulled down the images to my environment and I love it! Well done :)
