### ISSUE TITLE
List of icons for categories is very limited

### ISSUE THREAD

**Issue by avee87** [cioraneanu/firefly-pico#9]
I get that they look nice but it's very frustrating when you cannot find icons for some common use cases.

Examples:
- planes or air travel
- cats, dogs or pets in general
- electricity/gas

Would be great to incorporate [Material Design Icons](https://pictogrammers.com/library/mdi/) or some similar library of icons.

**Comment by cioraneanu** [comment]
I am not a fan of the look of Material Design Icons but I agree the icons diversity can be improved. 
They also need more synonims for each icon. For example instead of 'gas' currentyl you can search for 'flame'.

If anyone is interested in working on this before I get to it:
- for synonims [SvgConstants.js](https://github.com/cioraneanu/firefly-pico/blob/main/front/constants/SvgConstants.js) write a space separated list of words in the `name` key
- for new icons you can add them to `/front/assets/icons/fluent` from this repository [Microsoft Fluent System Icons](https://github.com/microsoft/fluentui-system-icons)

**Comment by cioraneanu** [comment]
Easy way to search inside Fluent icons: [Iconify](https://icon-sets.iconify.design/fluent/)

**Comment by e-labInnovations** [comment]
Hi, thanks for this great project!

I noticed the available icons for accounts are limited, and they vary by country (banks, shopping websites, etc.). I'd like to suggest adding an option for users to upload their own custom icons (SVG/PNG) that would then appear in the icon selection UI. This would offer more flexibility and personalization for users to better represent their accounts.

Thanks for considering this!

**Comment by cioraneanu** [comment]
Thank you! 😇 There will be more icons soon (and better search for them).
The option to let users upload SVGs sounds great in theory but require a lot of app changes which I don't think are worth it at the moment.

Most users are not willing to spend time searching the web for the perfect icon, so a big predefined list is just more convinient.

**Comment by cioraneanu** [comment]
If you have any favorites that integrate with the app aesthetics share a link and I'll gladly add them.

**Comment by cioraneanu** [comment]
Added more synonyms in 1.4.0 for better icon searching.

**Comment by cioraneanu** [comment]
Added more icons for accounts 😁

**Comment by cioraneanu** [comment]
Added more icons for accounts 😁
